# Generated by Django 4.0.6 on 2022-08-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower',
            name='membership_number',
        ),
        migrations.AlterField(
            model_name='borrower',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Ordered', 'Ordered'), ('Declined', 'Declined')], default='Pending', max_length=40),
        ),
    ]
