# Generated by Django 4.0.6 on 2022-08-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_borrower_membership_number_alter_borrower_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='google_books_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
